def register_general_keywords(waifu):
    waifu.registry.defkeyword("yes", [("yes", "Yes, that's right!"), ("yeah", "Yeah!"), ("yep", "Yup!"), ("yes", "Absolutely!"), ("yeah", "Totally!"), ("yep", "For sure!")])
    waifu.registry.defkeyword("no", [("no", "No, that's not right."), ("nope", "Nope!"), ("no", "Hmm, I don't think so."), ("nope", "Nah."), ("no", "Not really.")])
    waifu.registry.defkeyword("maybe", ["Maybe...", "Perhaps...", "I'm not sure.", "Possibly...", "Could be!"])
    waifu.registry.defkeyword("okay", [("okay", "Okay, I understand."), ("alright", "Alright, I get it."), ("okay", "Okay, what's next?"), ("alright", "Alright, let's do it!"), ("okay", "Okay, sounds good!")])
    waifu.registry.defkeyword("thanks", ["You're welcome!", "No problem!", "Anytime!", "Glad to help!"])
    waifu.registry.defkeyword("thank you", ["You're welcome!", "No problem!", "My pleasure!", "Don't mention it!"])
    waifu.registry.defkeyword("childhood", ["childhood"])
    waifu.registry.defkeyword("relationship", ["relationship"])
    waifu.registry.defkeyword("food", ["food"])
    waifu.registry.defkeyword("quirks", ["quirks"])
    waifu.registry.defkeyword("explain", ["Can you explain that?", "What do you mean?"])
    waifu.registry.defkeyword("context", ["I need more context.", "Can you give me some context?"])
    waifu.registry.defkeyword("what do you mean", ["What do you mean by that?", "Can you clarify?"])
    waifu.registry.defkeyword("clarify", ["Can you clarify that?", "I don't understand."])
    waifu.registry.defkeyword("doing", ["What are we doing?", "I'm not sure what we're doing."])
    waifu.registry.defsynonym("doing", "do")
    waifu.registry.defkeyword("sure", [("sure", "Sure, I guess."), ("yeah", "Yeah, I suppose."), ("sure", "Sure, why not?"), ("sure", "Sure, what do you mean?"), ("yeah", "Yeah, tell me more.")])
    waifu.registry.defkeyword("understand", [("understand", "I understand."), ("i see", "I see."), ("understand", "I get it now."), ("i see", "I see what you mean."), ("got it", "Gotcha!")])
    waifu.registry.defkeyword("got it", [("got it", "Got it."), ("ok", "Okay."), ("got it", "Gotcha!"), ("ok", "Okay, I'm with you."), ("got it", "I understand now.")])
    waifu.registry.defkeyword("tell me", [("tell me", "What do you want to know?"), ("tell me", "I'm all ears!"), ("tell me", "Okay, I'm listening.")])
    waifu.registry.defkeyword("and you", [("and you", "What about you?"), ("and you", "How about you?"), ("and you", "And you?")])
    waifu.registry.defsynonym("and you", "you")